### ISSUE TITLE
Deployment Guide?

### ISSUE THREAD

**Issue by siddhantj45** [robincsamuel/robincsamuel.github.io#3]
Really liked this design and wanted to do something with this, Is there a deployment guide and/or something you can link where I can fork it and deploy with changes on this?

Thanks.

**Comment by siddhantj45** [comment]
Deployment was a _config.yml file issue - Figured it out.

**Comment by robincsamuel** [comment]
@siddhantj45 Sorry, I didn't get notified and missed this. Glad you found it. Please let me know if you need any other info :)
